image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Initalise terraform
    init: |
      export TERRAFORM_AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
      export TERRAFORM_AWS_SECRET_ACCESS_KEY="$AWS_SECRETS_ACCESS_KEY"
      export TERRAFORM_AWS_DEFAULT_REGION="us-east-1"
    command: |
      terraform init
      terraform plan

  - name: aws-cli
    env:
       AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip "awscliv2.zip"
      sudo ./aws/install

vscode:
  extensions:
    - hashicorp.terraform